<a href="https://colab.research.google.com/github/jubatistim/GoogleColabsGeneral/blob/master/TensorFlow_01_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

Specify version of TensorFlow to be used in collab notebook

In [0]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.


Imports

In [0]:
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Tensor types

In [0]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


Shapes and rank

In [0]:
tensor1 = tf.Variable(["Test"], tf.string) 
tensor2 = tf.Variable([["test", "ok", "A"], ["test", "yes", "A"]], tf.string)
tensor3 = tf.Variable([[["1", "2", "3"], ["3", "4", "5"]],[["5", "6", "6"], ["7", "8", "7"]], [["5", "6", "6"], ["7", "8", "7"]]], tf.string)

#shape - ...groups x rows x columns
#rank - dimensions - deep of the arrays, [] = 1, [[]] = 2, [[[]]] = 3....

print(tensor1)
print("")
print(tensor2)
print("")
print(tensor3)
print("")
print(tf.rank(tensor1))
print("")
print(tf.rank(tensor2))
print("")
print(tf.rank(tensor3))

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'test', b'ok', b'A'],
       [b'test', b'yes', b'A']], dtype=object)>

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=string, numpy=
array([[[b'1', b'2', b'3'],
        [b'3', b'4', b'5']],

       [[b'5', b'6', b'6'],
        [b'7', b'8', b'7']],

       [[b'5', b'6', b'6'],
        [b'7', b'8', b'7']]], dtype=object)>

tf.Tensor(1, shape=(), dtype=int32)

tf.Tensor(2, shape=(), dtype=int32)

tf.Tensor(3, shape=(), dtype=int32)


Reshape

In [0]:
tensor4 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor5 = tf.reshape(tensor4, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor6 = tf.reshape(tensor5, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

print(tensor4)
print("")
print(tensor5)
print("")
print(tensor6)
print("")
print(tf.rank(tensor4))
print("")
print(tf.rank(tensor5))
print("")
print(tf.rank(tensor6))

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)

tf.Tensor(3, shape=(), dtype=int32)

tf.Tensor(3, shape=(), dtype=int32)

tf.Tensor(2, shape=(), dtype=int32)


Slicing Tensors

In [0]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [0]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print("selects the 3rd element from the 1st row")
print(three)  # -> 3
print("")

row1 = tensor[0]  # selects the first row
print("selects the first row")
print(row1)
print("")

column1 = tensor[:, 0]  # selects the first column
print("selects the first column")
print(column1)
print("")

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print("selects second and fourth row")
print(row_2_and_4)
print("")

column_1_in_row_2_and_3 = tensor[1:3, 0] # selects first column of second and third rows
print("selects first column of second and third rows")
print(column_1_in_row_2_and_3)
print("")

selects the 3rd element from the 1st row
tf.Tensor(3, shape=(), dtype=int32)

selects the first row
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

selects the first column
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)

selects second and fourth row
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)

selects first column of second and third rows
tf.Tensor([ 6 11], shape=(2,), dtype=int32)

